package com.altitudeengineering.replinteractiveinterpreter;

public enum TokenType { 
	TOKEN_OPEN_PARENTHESES,
	TOKEN_CLOSED_PARENTHESES,
	TOKEN_PLUS,
	TOKEN_MINUS,
	TOKEN_MULTIPLY,
	TOKEN_DIVIDE,
	TOKEN_MOD,
	TOKEN_ASSIGN,
	TOKEN_FUNCTION,
	TOKEN_IDENTIFIER,
	TOKEN_INTEGER,
	TOKEN_DOUBLE,
	END_OF_FUNCTION 
}
